[application]

# dioxus project name
name = "doskvol-ltd"

# default platform
# you can also use `dx serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

# hot reload by default
hot_reload = true

[web.wasm_opt]
# The level wasm-opt should target. z is the smallest. 4 is the fastest.
level = "4"

[web.app]

# HTML title tag content
title = "Doskvol-Ltd"

[web.watcher]

index_on_404 = true

watch_path = ["src", "api", "data", "types", "assets"]

[bundle]
# Bundle identifier
identifier = "miitto.dev.doskvol-ltd"

# Bundle publisher
publisher = "miitto.dev"

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = []

# Bundle copyright
copyright = ""

# Bundle category
category = "Application"

# Bundle short description
short_description = "An app for managing Blades in the Dark games."

# Bundle long description
long_description = """
An app for managing Blades in the Dark games.
"""
