CREATE TABLE sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  token TEXT NOT NULL UNIQUE,
  user_id TEXT NOT NULL,
  name TEXT,
  FOREIGN KEY (user_id) REFERENCES users(username) ON DELETE CASCADE
)
