[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
tracing.workspace = true

types.workspace = true

rusqlite = { version = "0.37.0", features = ["bundled"], optional = true }

[features]
server = ["dep:rusqlite", "types/server"]
