[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
api = { workspace = true }
ui = { workspace = true }
types = { workspace = true }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "api/server"]
